sequences:
  - name: istio_http_requests_total
    type: counter
    help: "Total number of HTTP requests"
    data:
      - value: 1
        times: 5
        interval: 1
        labels:
          source: app
          service: web
          response_code: "200"
      - value: 1
        times: 5
        interval: 1
        labels:
          source: app
          service: web
          response_code: "400"
      - value: 1
        times: 5
        interval: 1
        labels:
          source: app
          service: web
          response_code: "500"
